Dataset: https://archive.ics.uci.edu/dataset/109/wine

In [18]:
!pip install pandas
!pip install matplotlib
!pip install ucimlrepo
!pip install graphviz
!pip install pydotplus
!pip install scikit-learn
!pip install --upgrade category_encoders

In [1]:
import numpy as np
import pandas as pd
from ucimlrepo import fetch_ucirepo
from sklearn.ensemble import RandomForestClassifier  # Import the Random Forest classifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier  # Import the KNN classifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix

# Fetch dataset
wine = fetch_ucirepo(id=109)

# Data
X = wine.data.features  # Features
y = wine.data.targets  # Target variable

# Get a list of feature column names
feature_cols = list(X.columns.values)

# Verify the number of unique classes in the target variable
num_classes = len(np.unique(y))

# Define class names based on the number of unique classes
class_names = [str(i) for i in range(num_classes)]

# Split data into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)  # 70% training, 30% testing

# Create a Random Forest classifier and fit it to the data (TRAIN DATA)
clf_rf = RandomForestClassifier()
clf_rf = clf_rf.fit(X_train, y_train)

# Make predictions with Random Forest
y_pred_rf = clf_rf.predict(X_test)

# Print Random Forest accuracy
print("Random Forest Accuracy:", metrics.accuracy_score(y_test, y_pred_rf))

# Calculate the Random Forest confusion matrix
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)

# Print the Random Forest confusion matrix
print(f"Random Forest Confusion Matrix: \n{conf_matrix_rf}")

# Create an SVM classifier and fit it to the data (TRAIN DATA)
clf_svm = SVC(kernel="linear")
clf_svm = clf_svm.fit(X_train, y_train)

# Make predictions with SVM
y_pred_svm = clf_svm.predict(X_test)

# Print SVM accuracy
print("SVM Accuracy:", metrics.accuracy_score(y_test, y_pred_svm))

# Calculate the SVM confusion matrix
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)

# Print the SVM confusion matrix
print(f"SVM Confusion Matrix: \n{conf_matrix_svm}")

# Create a K-Nearest Neighbors (KNN) classifier and fit it to the data (TRAIN DATA)
clf_knn = KNeighborsClassifier(n_neighbors=5)
clf_knn = clf_knn.fit(X_train, y_train)

# Make predictions with KNN
y_pred_knn = clf_knn.predict(X_test)

# Print KNN accuracy
print("KNN Accuracy:", metrics.accuracy_score(y_test, y_pred_knn))

# Calculate the KNN confusion matrix
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)

# Print the KNN confusion matrix
print(f"KNN Confusion Matrix: \n{conf_matrix_knn}")


c:\Users\jarne\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Random Forest Accuracy: 0.9814814814814815
Random Forest Confusion Matrix: 
[[19  0  0]
 [ 0 21  1]
 [ 0  0 13]]


c:\Users\jarne\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM Accuracy: 0.9814814814814815
SVM Confusion Matrix: 
[[19  0  0]
 [ 0 21  1]
 [ 0  0 13]]
KNN Accuracy: 0.7037037037037037
KNN Confusion Matrix: 
[[16  1  2]
 [ 2 18  2]
 [ 4  5  4]]


c:\Users\jarne\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
